<a href="https://colab.research.google.com/github/yaryan/PyTorch-Basics/blob/main/pytorchtrainingpipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns= ['id', "Unnamed: 32"], inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   diagnosis                569 non-null    object
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null    float64
 15  smoothness_se            569 non-null    float64
 16  compactness_se           569 non-null    float64
 17  concavity_se             569 non-null    float64
 18  concave points_se        569 non-null    float64
 19  symmetry_se              569 non-null    float64
 20  fractal_dimension_se     569 non-null    float64
 21  radius_worst             569 non-null    float64
 22  texture_worst            569 non-null    float64
 23  perimeter_worst          569 non-null    float64
 24  area_worst               569 non-null    float64
 25  smoothness_worst         569 non-null    float64
 26  compactness_worst        569 non-null    float64
 27  concavity_worst          569 non-null    float64
 28  concave points_worst     569 non-null    float64
 29  symmetry_worst           569 non-null    float64
 30  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), object(1)
memory usage: 137.9+ KB

## train test split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], train_size= 0.2)

## scaling

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
print(df['diagnosis'].unique())

['M' 'B']

In [ ]:
X_train

array([[-0.8425815 , -1.06435271, -0.87514281, ..., -1.08764949,
        -1.65029427, -0.57198223],
       [-0.40522868,  0.98846905, -0.41255153, ...,  0.07782786,
        -0.24318381,  0.62413436],
       [-0.01899502,  0.02413053, -0.00684983, ...,  1.08405131,
         0.29438111,  1.13216804],
       ...,
       [ 0.25932042, -0.09114671,  0.2385644 , ...,  0.55838898,
        -0.03607665,  0.03818464],
       [-0.97889926, -0.12439977, -0.9137613 , ..., -0.52466203,
        -0.06957928, -0.42773226],
       [-0.37682914, -0.40815914, -0.42791587, ..., -1.19558134,
        -1.24978556, -1.25006242]])

In [ ]:
y_train

173    B
228    B
435    M
139    B
557    B
      ..
80     B
333    B
291    B
266    B
429    B
Name: diagnosis, Length: 113, dtype: object

## Label Encoding

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [ ]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0])

## Numpy arrays to PyTorch Tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([113, 30])

## Defining the model

In [ ]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

## important paramertes

In [ ]:
learning_rate = 0.1
epochs = 25

## Training Pipeline

In [ ]:
# Create Model
model = MySimpleNN(X_train_tensor)
# model.weights

# for training the model
# all the below steps are defined under a loop that transfer for the number of ephocs
# first, we take the forward pass,
# second we, calculate the loss
# third we take the backward pass
# lastly, we update the parameters

# define loop
# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)
  print(f'epoch: {epoch}, loss: {loss}')

  # backward pass
  loss.backward() # backpropagation to create derivatives

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero the gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'epoch: {epoch}, loss: {loss}')

epoch: 0, loss: 3.4438652738237234
epoch: 0, loss: 3.4438652738237234
epoch: 1, loss: 3.281426871057347
epoch: 1, loss: 3.281426871057347
epoch: 2, loss: 3.1210971083624113
epoch: 2, loss: 3.1210971083624113
epoch: 3, loss: 2.963194137040226
epoch: 3, loss: 2.963194137040226
epoch: 4, loss: 2.808076172468441
epoch: 4, loss: 2.808076172468441
epoch: 5, loss: 2.6560856271651767
epoch: 5, loss: 2.6560856271651767
epoch: 6, loss: 2.4920207998533392
epoch: 6, loss: 2.4920207998533392
epoch: 7, loss: 2.3197304805609993
epoch: 7, loss: 2.3197304805609993
epoch: 8, loss: 2.1454808528490266
epoch: 8, loss: 2.1454808528490266
epoch: 9, loss: 1.9787301146537533
epoch: 9, loss: 1.9787301146537533
epoch: 10, loss: 1.820842691925591
epoch: 10, loss: 1.820842691925591
epoch: 11, loss: 1.6732697591245957
epoch: 11, loss: 1.6732697591245957
epoch: 12, loss: 1.537337959497982
epoch: 12, loss: 1.537337959497982
epoch: 13, loss: 1.4140434530339565
epoch: 13, loss: 1.4140434530339565
epoch: 14, loss: 1.3039815017934715
epoch: 14, loss: 1.3039815017934715
epoch: 15, loss: 1.2073866038083665
epoch: 15, loss: 1.2073866038083665
epoch: 16, loss: 1.1241378450013302
epoch: 16, loss: 1.1241378450013302
epoch: 17, loss: 1.0536860113009818
epoch: 17, loss: 1.0536860113009818
epoch: 18, loss: 0.9950036976807496
epoch: 18, loss: 0.9950036976807496
epoch: 19, loss: 0.9466637436545902
epoch: 19, loss: 0.9466637436545902
epoch: 20, loss: 0.9070415668399588
epoch: 20, loss: 0.9070415668399588
epoch: 21, loss: 0.8745440604313145
epoch: 21, loss: 0.8745440604313145
epoch: 22, loss: 0.8477708747285954
epoch: 22, loss: 0.8477708747285954
epoch: 23, loss: 0.8255777484000627
epoch: 23, loss: 0.8255777484000627
epoch: 24, loss: 0.8070657618411033
epoch: 24, loss: 0.8070657618411033

In [ ]:
model.weights

tensor([[ 0.1603],
        [-0.1697],
        [ 0.3110],
        [ 0.0207],
        [-0.0362],
        [-0.1345],
        [ 0.2653],
        [ 0.4108],
        [-0.2220],
        [ 0.2789],
        [ 0.3496],
        [ 0.2216],
        [-0.4175],
        [-0.0823],
        [ 0.4627],
        [-0.0829],
        [-0.0526],
        [ 0.3606],
        [ 0.3167],
        [ 0.0672],
        [-0.1068],
        [-0.0059],
        [ 0.0182],
        [-0.1695],
        [-0.1430],
        [-0.0827],
        [-0.0690],
        [-0.3375],
        [ 0.2361],
        [-0.0599]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([-0.1265], dtype=torch.float64, requires_grad=True)

## Evaluation

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")
# print(y_pred)

Accuracy: 0.6240381598472595